# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 03:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='card_id',
            new_name='card',
        ),
        migrations.RenameField(
            model_name='log',
            old_name='member_id',
            new_name='member',
        ),
    ]
