# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 04:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_log_status_at_scan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cards.Card'),
        ),
        migrations.AlterField(
            model_name='log',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='members.Member'),
        ),
    ]
