# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_auto_20170224_0421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='card',
        ),
        migrations.RemoveField(
            model_name='log',
            name='member',
        ),
        migrations.AddField(
            model_name='log',
            name='member_name',
            field=models.CharField(default=' ', max_length=255, verbose_name='Member Name'),
            preserve_default=False,
        ),
    ]
