# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20170224_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card',
            field=models.CharField(max_length=255, verbose_name='Card ID'),
        ),
    ]
