# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 04:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_auto_20170224_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Member'),
        ),
    ]
