# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Member Name')),
                ('notes', models.TextField(verbose_name='Notes')),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], verbose_name='Status')),
            ],
        ),
    ]
